import Head from 'next/head'
//import Image from 'next/image'
import Header from '../components/Header'
//import Banner from '../components/Banner'
//import About from '../components/About'
import Vote from '../components/Vote'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Hominid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head> 

      <Header /> 
      
      {/* <Banner /> */} 

      {/* <About /> */}

      <Vote />

      {/* Vote */}
      {/* Community */}


      {/*Footer*/}

      
    </div>
  )
}
